#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Adrien RICCIARDI

# The script will start right after the network-control script and will stop right before it
START=24
STOP=86

boot() {
	raspivid -w 640 -h 480 -b 1000000 -t 0 -fps 24 -n -ih -vs -ex auto -o - | fast-network-transfer 1235&
}